- hosts: webServer-master
  vars_files:
    - host_vars/nectar.yaml
    - host_vars/server.yaml
  gather_facts: true

  roles:
    - role: proxy-env
    - role: webServer-master


- hosts: webServer-worker
  vars_files:
    - host_vars/nectar.yaml
    - host_vars/server.yaml
  gather_facts: true

  roles:
    - role: proxy-env
    - role: webServer-worker



