# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: master-volume
    vol_size: 20
  - vol_name: server1-volume
    vol_size: 20
  - vol_name: server2-volume
    vol_size: 20

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_https
    description: "Demo security group for HTTPS"
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_couchdb
    description: "Security group for couchdb"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_couchdb
    description: "Security group for couchdb"
    protocol: tcp
    port_range_min: 5986
    port_range_max: 5986
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_couchdb
    description: "Security group for couchdb"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_couchdb
    description: "Security group for couchdb"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: master
    volumes: ['master-volume']
  - name: server1
    volumes: ['server1-volume']
  - name: server2
    volumes: ['server2-volume']

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: f-key
instance_flavor: uom.mse.2c9g
